---
title: "Apuntes FP2"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'FP2.html'))})
output: 
  html_document:
    includes:
      in_header: "layouts/partials/favicon.html" 
---


### Índice

- [Álgebra (ecuaciones)](#-lgebra--ecuaciones-)
    + [Regla de 3](#regla-de-3)
- [Análisis (funciones)](#an-lisis--funciones-)
- [Probabilidad y estadística](#probabilidad-y-estad-stica)
  * [Probabilidad](#probabilidad)
    + [Regla de Laplace](#regla-de-laplace)
  * [Estadística](#estad-stica)
- [Geometría](#geometr-a)
* [Anexo I: Exámenes trabajados.](#anexo-i--ex-menes-trabajados)

## Álgebra (ecuaciones)

#### Regla de 3

Esta regla se usa para casos de proporcionalidad directa, donde cuando dos magnitudes están relacionadas y un crecimiento en una de ellas provoca un crecimiento en la otra. El uso típico es en porcentajes. En general, **multiplicamos en diagonal y dividimos por el número que falta**.

- <details><summary>Ejemplo 1 (pincha para expandir)</summary>
<br>
  Si un pantalón cuesta 24€ y lo rebajan un 20%, ¿cuánto cuesta ahora?
  \begin{cases}
    100\% \longrightarrow 24€ \\
    \quad \quad \quad \quad \quad \quad \quad \Rightarrow x = \frac{80 \times 24}{100} = 19.2€ \\ 
    80\% \longrightarrow x\\
  \end{cases}
</details>
- <details><summary>Ejemplo 2 (pincha para expandir)</summary>
<br>
  Si una colonia cuesta 12€ sin IVA y el IVA es del 14%, ¿cuál es el precio final de la colonia?
  \begin{cases}
    100\% \longrightarrow 12€ \\
    \quad \quad \quad \quad \quad \quad \quad \Rightarrow x = \frac{114 \times 12}{100} = 13.68€ \\ 
    114\% \longrightarrow x\\
  \end{cases}
</details>

## Análisis (funciones)

## Probabilidad y estadística

### Probabilidad

#### Regla de Laplace

La regla de Laplace es aquella que usamos para calcular la probabilidad de que un suceso ocurra. En general, es el cociente entre los casos favorables y los casos posibles. Es importante tener en cuenta que **la probabilidad de un suceso siempre es un número que está entre 0 y 1**.

\begin{gather*}
  P(X) = \frac{\text{Casos favorables}}{\text{Casos posibles}}
\end{gather*}

Para calcular probabilidades, es necesario modelar el problema previamente. Esto es, establecer una estructura que nos permita enfocar el problema y poder entenderlo apropiadamente. En general, los modelos que emplearemos serán:

1. Modelos aplicando diagramas de Venn.
2. Modelos de diagramas de árbol.
3. Modelos de urnas.

- <details><summary>Ejemplo 1: urnas (pincha para expandir)</summary>

  Si en una caja tenemos 8 bolas, de las cuales 2 son amarillas, 2 son rojas, 2 son verdes y 2 son de los tres colores anteriores, calcula:
  a) La probabilidad de sacar una bola solamente amarilla.
  b) La probabilidad de sacar una bola que tenga el color verde.
  c) La probabilidad de sacar una bola que no tenga rojo.
  
  Resolución: Es recomendable dibujar la urna para ver los casos más fácilmente.
  
  a) 
  \begin{gather*}
     P(\text{Sacar una bola solo amarilla}) = \frac{\text{Casos favorables}}{\text{Casos posibles}} = \frac{2}{8} = \frac{1}{4} = 0.25
  \end{gather*}
  b)
  \begin{gather*}
     P(\text{Sacar una bola que tenga verde}) = \frac{\text{Casos favorables}}{\text{Casos posibles}} = \frac{4}{8} = \frac{1}{2} = 0.5
  \end{gather*}
  c) 
  \begin{gather*}
     P(\text{Sacar una bola que no tenga rojo}) = \frac{\text{Casos favorables}}{\text{Casos posibles}} = \frac{4}{8} = \frac{1}{2} = 0.5
  \end{gather*}
  
</details>

### Estadística

Para el bloque de estadística, nos bastará con saber calcular los estadísticos más importantes, aplicando las siguientes fórmulas:


| Nombre   |      Símbolo/s      |  Fórmula | Uso |
|:----------:|:-------------:|:------:|:------:|
| <br>Media |  $$\overline{X}, \mu$$ | $$\frac{1}{n} \sum x_i$$ | <br>Una sola variable |
| <br>Varianza |  $$Var(X), \sigma_X^2$$ | $$\frac{1}{n} \sum (x_i-\overline{X})^2$$ | <br>Una sola variable |
| <br>Desviación estándar |  $$\sigma_X$$ | $$\sqrt{\frac{1}{n} \sum (x_i-\overline{X})^2}$$ | <br>Una sola variable |
| <br>Covarianza |  $$Cov(X,Y), \sigma_{XY}$$ | $$\frac{1}{n} \sum (x_i-\overline{X})(y_i-\overline{Y})$$ | <br>Dos variables |
| <br>Coeficiente de correlación |  $$\rho_{XY}$$ | $$\frac{\sigma_{XY}}{\sigma_{Y}\sigma_{Y}} $$ | <br>Dos variables |

- <details><summary>Ejemplo 1 (pincha para expandir)</summary>
<br>
  Supongamos que tenemos las siguientes variables:
  
  \begin{cases}
   X \text{ que toma los valores } 7,6,3,4,5\\
   Y \text{ que toma los valores } 5,4,1,3,5\\
  \end{cases}
  
  Entonces tenemos que:
  
  \begin{gather*}
    \overline{X} = \frac{7+6+3+4+5}{5} = \frac{25}{5} = 5\\
    \overline{Y} = \frac{5+4+1+3+5}{5} = \frac{18}{5} = 3.6\\ \\
    \hline\\
    Var(X) = \frac{1}{5}\left[ (7-5)^2+(6-5)^2+(3-5)^2+(4-5)^2+(5-5)^2 \right] = \frac{10}{5} = 2\\
    Var(Y) = \frac{1}{5}\left[ (5-3.6)^2+(4-3.6)^2+(1-3.6)^2+(3-3.6)^2+(5-3.6)^2 \right] = \frac{11.2}{5} = 2.24\\ \\
    \hline\\
    \sigma_X = \sqrt{Var(X)} = 1.4142\\
    \sigma_Y = \sqrt{Var(Y)} = 1.4966\\ \\
    \hline\\
    Cov(X,Y) = \frac{1}{5}\left[ (7-5)(5-3.6)+(6-5)(4-3.6)+(3-5)(1-3.6)+(4-5)(3-3.6)+(5-5)(5-3.6) \right] = \frac{9}{5} = 1.8 \\ \\
    \hline\\
    \rho_{XY} = \frac{\sigma_{XY}}{\sigma_{Y}\sigma_{Y}} = \frac{1.8}{1.4142 \times 1.4966} = 0.85042
  \end{gather*}
  
</details>




## Geometría

### Anexo I: Exámenes trabajados.

- 2021/06/01: Prueba ordinaria 2020 (ejercicios 1-4). El 4to ejercicio era de maximizar parábolas, comprobar en un futuro si hay que derivar o aplicar fórmula de extremos. 




<!-- 
for using a collapse-able list-item:

- example 1
- example 2
- <details><summary>example 3 (click to expand)</summary>

  ```text
  weee
    weee
  weee
  ```
  `note the newlines and indents - and the \ was added in front of ``` to escape the code-section (remove it for actual use)`
</details>

- example 4 -->